### PR TITLE
Fix source file not endof .pcap or .pcapng error

### PR DESCRIPTION
**Pull request by hallelujah-shih**
# Pull Request Template

## Description

Please include a summary of the change and which issue is fixed. 
Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. 
Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* OS version:
* Python version:
* Hardware:

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by aouinizied** [comment]
As we definitively do not check properly for file type as proposed by @drnpkr in https://github.com/nfstream/nfstream/pull/88 because it adds a new dependency.
We can be more permissive regarding file naming.

Thanks for your contribution.

**Comment by hallelujah-shih** [comment]
> As we definitively do not check properly for file type as proposed by @drnpkr in #88 because it adds a new dependency. We can be more permissive regarding file naming.
> 
> Thanks for your contribution.

libpcap while check  interface or file is invalid, so i delete file extention check

**Comment by drnpkr** [comment]
> > As we definitively do not check properly for file type as proposed by @drnpkr in #88 because it adds a new dependency. We can be more permissive regarding file naming.
> > Thanks for your contribution.
> 
> libpcap while check interface or file is invalid, so i delete file extention check

Or we could create a more comprehensive regular expression. In my experience, problems source mianly from either no extension at all (e.g. mydump) or the extension includes numbering (e.g. mydump.pcap0, mydump.pcap1, etc.). 

Anyway, I agree, we shall keep the number of dependencies as low as possible.

**Comment by hallelujah-shih** [comment]
> > > As we definitively do not check properly for file type as proposed by @drnpkr in #88 because it adds a new dependency. We can be more permissive regarding file naming.
> > > Thanks for your contribution.
> > 
> > 
> > libpcap while check interface or file is invalid, so i delete file extention check
> 
> Or we could create a more comprehensive regular expression. In my experience, problems source mianly from either no extension at all (e.g. mydump) or the extension includes numbering (e.g. mydump.pcap0, mydump.pcap1, etc.).
> 
> Anyway, I agree, we shall keep the number of dependencies as low as possible.

i agree, thanks

**Pull request merged**
