### PR TITLE
Ignored packets plugin callback

### PR DESCRIPTION
**Pull request by Schwaggot**
## Description

Adds a callback function to NFPlugin `on_ignore()` which is called whenever the engine ignores a packet, i.e., does no flow analysis on it.

Motivation behind it is to be able to react upon every packet in the capture, e.g., to match packet labels to flows. If we have a capture file with n packets and we have another CSV file with n labels (one for each packet) we like to propagate the packet based labels to flow labels. The current issue is that we cannot correlate the seen packets in NFStream to the index in the CSV file. This is because we do not see all the packets, e.g., non-IP, broadcast packets etc. are not visible in the NFPlugin callbacks.

TL;DR: At the moment we do not know which packets from a capture are ignored by NFStream, this adds a callback for ignored packets.

## Type of change
- [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

An example has been provided in the `examples/` folder.

**Test Configuration**:
* OS version: Debian 11
* Python version: 3.9

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by aouinizied** [comment]
@Schwaggot can you rebase this branch as merging https://github.com/nfstream/nfstream/pull/131 results in conflicts with this PR.

**Comment by Schwaggot** [comment]
@aouinizied Sorry, completely forgot about this, just updated the branch to include recent changes.

**Comment by Schwaggot** [comment]
@aouinizied If there is anything from my side still to be done, just let me know.

**Comment by aouinizied** [comment]
@Schwaggot  Thank you for this PR. However after reviewing it. I think this PR cannot be merged as it is for the following reasons:

* Ignored packets (non IP) do not belong to any flow, consequently, any logic cannot be handled within a flow lifecycle (NFPlugin entrypoints).
* The way you impelmented it will works for debug purposes but this entrypoint is confusing for users.

I think we obviously do need more logging in NFStream, such as logging ignored packets (or even storing them), but this must be implemented as part of nfstream logging and not in the NFPlugin.

If you think you will have time to implement it this way, do not hesitate to open a PR.

Thanks again!

Zied

**Pull request closed without merging**
